services:
   postgres-data:
      container_name: postgresdb
      image: postgres:alpine
      environment:
         POSTGRES_DB: ${POSTGRES_DB:-postgres}
      	POSTGRES_USER: ${POSTGRES_USER:-postgres}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
         PGDATA: /data/postgres
      ports:
         - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
      networks:
         - public
      restart: unless-stopped
      volumes:
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql

   timescaledb:
      container_name: timescaledb
      image: timescale/timescaledb-ha:pg15-all
      environment:
         POSTGRES_DB: ${POSTGRES_DB:-postgres}
      	POSTGRES_USER: ${POSTGRES_USER:-postgres}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      networks:
         - public
      restart: unless-stopped
      volumes:
         - "/data/pgdata:/home/postgres/pgdata"
         - "/data/oldtimescale:/mnt/olddata"

networks:
  public:
    external: true

volumes:
    postgres:
