services:
  neo4j:
    image: neo4j:latest
    container_name: ${NEO4J_HOST:-neo4j_db}
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugin:/plugins
    environment:
        # - NEO4J_AUTH_FILE=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-my_password}
        - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
        - NEO4J_PLUGINS=["graph-data-science"]
    ports:
      - "${NEO4J_PORT:-7474}:${NEO4J_PORT:-7474}"
      - "7687:7687"
    restart: always
    secrets:
      - neo4j_auth_file
    networks:
      - public

networks:
  public:
    external: true
    
secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt
